/**
 * IKseService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package at.chipkarte.client.kse.soap;

public interface IKseService extends java.rmi.Remote {
    public at.chipkarte.client.base.soap.Property[] checkStatus(java.lang.String dialogId) throws java.rmi.RemoteException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.Limit[] getLimit(java.lang.String dialogId, int zeitraum) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.ErgebnisKonsultation doKonsultation(java.lang.String cin, java.lang.String dialogId, java.lang.String svNummer, java.lang.String svtCode, java.lang.String anspruchId, java.lang.String fachgebietsCode, java.lang.String behandlungsfallCode, java.lang.String nacherfassungsgrundCode, java.lang.String behandlungsdatum, boolean forceExecution, java.lang.String cardReaderId) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.CardException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.BCardException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public void sendZusatzinformationsAntwort(java.lang.String dialogId, long zusatzinformationsAntwortId, int zusatzinformationsAntwort) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.DialogException, at.chipkarte.client.base.soap.exceptions.ServiceException;
    public at.chipkarte.client.kse.soap.OfflineRecord doKonsultationOffline(java.lang.String cin, java.lang.String dialogId, java.lang.String svNummer, java.lang.String svtCode, java.lang.String fachgebietsCode, java.lang.String behandlungsfallCode, java.lang.String nacherfassungsgrundCode, java.lang.String behandlungsdatum, boolean forceExecution, java.lang.String cardReaderId) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.CardException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.KonsultationsBeleg stornierenKonsultation(java.lang.String dialogId, long konsId, int konsVersion) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.ErgebnisKonsultation wiederinkraftsetzenKonsultation(java.lang.String dialogId, long konsId, int konsVersion) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.KonsultationsBeleg aendernKonsultation(java.lang.String dialogId, long konsId, int konsVersion, java.lang.String behandlungsfallCode) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.Konsultationsdaten[] getKonsultationsdaten(java.lang.String dialogId, at.chipkarte.client.kse.soap.SuchFilter selektionsKriterien, java.lang.String selektionsart) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public java.lang.String sendKonsultationsdatenAnfrage(java.lang.String dialogId, at.chipkarte.client.kse.soap.SuchFilter selektionsKriterien) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.Konsultationsdaten[] downloadKonsultationsdaten(java.lang.String dialogId, java.lang.String anfrageId) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.KonsultationdatenAnfrage[] getKonsultationsdatenAnfragen(java.lang.String dialogId, boolean onlyReady) throws java.rmi.RemoteException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public void deleteKonsultationsdatenAnfrage(java.lang.String dialogId, java.lang.String anfrageId) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.KonsultationsBeleg[] nachsignierenKonsultationen(java.lang.String dialogId, java.lang.String cin, boolean forceExecution, java.lang.String cardReaderId) throws java.rmi.RemoteException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.CardException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.KonsultationsBeleg[] nachsignierenKonsultationenBCard(java.lang.String dialogId, java.lang.String svNummer, java.lang.String cardReaderId) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.CardException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.BCardException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.OfflineRecord nachsignierenKonsultationenOffline(java.lang.String dialogId, java.lang.String cin, boolean forceExecution, java.lang.String cardReaderId) throws java.rmi.RemoteException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.base.soap.exceptions.CardException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.base.soap.BaseProperty[] getBehandlungsfaelle() throws java.rmi.RemoteException, at.chipkarte.client.base.soap.exceptions.ServiceException;
    public at.chipkarte.client.base.soap.BaseProperty[] getBehandlungsfaelleByFachgebiet(java.lang.String fachgebietCode) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.ServiceException;
    public at.chipkarte.client.kse.soap.OfflineRecord[] getOfflineRecords(java.lang.String dialogId) throws java.rmi.RemoteException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public long getNumberOfflineKonsultationen(java.lang.String dialogId) throws java.rmi.RemoteException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public long getNumberOfflineNachsignaturen(java.lang.String dialogId) throws java.rmi.RemoteException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public void deleteOfflineRecord(java.lang.String dialogId, java.lang.String offlineId) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.ErgebnisKonsultation sendOfflineKonsultation(java.lang.String dialogId, java.lang.String offlineId, java.lang.String fachgebietsCode, java.lang.String behandlungsfallCode, java.lang.String svtCode, java.lang.String anspruchId) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
    public at.chipkarte.client.kse.soap.KonsultationsBeleg[] sendOfflineNachsignatur(java.lang.String dialogId, java.lang.String offlineId) throws java.rmi.RemoteException, at.chipkarte.client.kse.soap.exceptions.InvalidParameterException, at.chipkarte.client.base.soap.exceptions.AccessException, at.chipkarte.client.kse.soap.exceptions.KseException, at.chipkarte.client.base.soap.exceptions.ServiceException, at.chipkarte.client.base.soap.exceptions.DialogException;
}
